workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      # android_signing:
      #   - keystore_reference
      # Uncomment above and add keystore in Codemagic dashboard (Code signing identities)
      # to enable signed release builds
      groups:
        - google_play
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_VERSION: "3.0.0"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate app icons
        script: |
          flutter pub run flutter_launcher_icons
        ignore_failure: true
      - name: Verify Android permissions
        script: |
          echo "Checking Android permissions..."
          grep -q "android.permission.VIBRATE" android/app/src/main/AndroidManifest.xml && echo "✓ VIBRATE permission found" || echo "⚠ VIBRATE permission missing"
          grep -q "android.permission.CAMERA" android/app/src/main/AndroidManifest.xml && echo "✓ CAMERA permission found" || echo "⚠ CAMERA permission missing"
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_VERSION: "3.0.0"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate app icons
        script: |
          flutter pub run flutter_launcher_icons
        ignore_failure: true
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter build iOS (simulator - debug)
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

  # 공스타그램 프로덕션 빌드 워크플로우
  gongstagram-production:
    name: 공스타그램 Production Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        # Uncomment and configure in Codemagic dashboard for signed releases
        # - keystore_reference
      groups:
        - google_play
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PACKAGE_NAME: "com.gongstagram.note"
        APP_NAME: "공스타그램"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true
    scripts:
      - name: Set up build info
        script: |
          echo "Building 공스타그램 (Digital Note)"
          echo "Branch: $CM_BRANCH"
          echo "Commit: $CM_COMMIT"

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Generate app launcher icons
        script: |
          echo "Generating app icons with primary color #667EEA..."
          flutter pub run flutter_launcher_icons

      - name: Verify project configuration
        script: |
          echo "=== Verifying Dependencies ==="
          grep "vibration:" pubspec.yaml && echo "✓ Haptic feedback (vibration) configured" || echo "⚠ Missing vibration package"
          grep "google_fonts:" pubspec.yaml && echo "✓ Google Fonts configured" || echo "⚠ Missing google_fonts"
          grep "shared_preferences:" pubspec.yaml && echo "✓ SharedPreferences configured" || echo "⚠ Missing shared_preferences"

          echo ""
          echo "=== Verifying Android Configuration ==="
          grep -q "android.permission.VIBRATE" android/app/src/main/AndroidManifest.xml && echo "✓ VIBRATE permission" || echo "⚠ Missing VIBRATE"
          grep -q "android.permission.CAMERA" android/app/src/main/AndroidManifest.xml && echo "✓ CAMERA permission" || echo "⚠ Missing CAMERA"
          grep -q "#667EEA" android/app/src/main/res/values/styles.xml && echo "✓ Splash screen color set" || echo "⚠ Splash screen not configured"

          echo ""
          echo "=== Checking Key Files ==="
          [ -f "lib/screens/splash_screen.dart" ] && echo "✓ Splash screen implemented" || echo "⚠ Missing splash screen"
          [ -f "lib/services/haptic_service.dart" ] && echo "✓ Haptic feedback service" || echo "⚠ Missing haptic service"
          [ -f "lib/screens/gesture_guide_screen.dart" ] && echo "✓ Gesture guide implemented" || echo "⚠ Missing gesture guide"
          [ -f "lib/utils/page_routes.dart" ] && echo "✓ Page animations configured" || echo "⚠ Missing page routes"
          [ -f "lib/widgets/today_study_card.dart" ] && echo "✓ Today study card widget" || echo "⚠ Missing study card"

      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos

      - name: Run tests
        script: |
          flutter test
        ignore_failure: true

      - name: Build Android APK (Release)
        script: |
          flutter build apk --release --target-platform android-arm64

      - name: Build Android App Bundle (Release)
        script: |
          flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
      scripts:
        - name: Build summary
          script: |
            echo "=== 공스타그램 Build Complete ==="
            echo "Features included:"
            echo "  ✓ Splash screen with brand animation"
            echo "  ✓ Haptic feedback (9 patterns)"
            echo "  ✓ Page transition animations (6 types)"
            echo "  ✓ Gesture guide (first-time user tutorial)"
            echo "  ✓ S-Pen/Apple Pencil support with pressure detection"
            echo "  ✓ Zoom & Pan gestures"
            echo "  ✓ Background customization (images, templates, colors)"
            echo "  ✓ Custom font support"
            echo "  ✓ Study timer & statistics"
            echo "  ✓ Today's study card with motivation"

  # 테스트 및 검증 워크플로우
  test-and-verify:
    name: Test & Code Quality
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        FLUTTER_VERSION: "3.0.0"
    triggering:
      events:
        - pull_request
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Flutter analyze (strict)
        script: |
          flutter analyze

      - name: Check code formatting
        script: |
          flutter format --set-exit-if-changed lib/
        ignore_failure: true

      - name: Run unit tests
        script: |
          flutter test --coverage
        ignore_failure: true

      - name: Verify UX features
        script: |
          echo "=== UX Features Check ==="
          # Splash screen
          grep -q "SplashScreen" lib/main.dart && echo "✓ Splash screen integrated in main.dart" || echo "⚠ Splash screen not in main"

          # Haptic feedback
          grep -rq "hapticService" lib/ && echo "✓ Haptic feedback used in codebase" || echo "⚠ Haptic feedback not used"

          # Page routes
          grep -rq "PageRoutes\|pushSlideRight\|pushSlideUp" lib/ && echo "✓ Custom page animations used" || echo "⚠ Page animations not used"

          # Gesture guide
          grep -q "GestureGuideScreen.shouldShow" lib/screens/home_dashboard.dart && echo "✓ Gesture guide auto-shows on first launch" || echo "⚠ Gesture guide not configured"

      - name: Build debug APK for testing
        script: |
          flutter build apk --debug

    artifacts:
      - build/**/outputs/**/*.apk
      - coverage/lcov.info

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: false
          failure: true
